// import React from "react";
// import Head from "next/head";

// import Footer from "../../common/Footer";
// import Header from "../header/Header";

// function Layout({ children }) {
//   return (
//     <>
//       <Head>
//         <title>Corelaw - Law firm</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/assets/images/icons/logo-icon.svg" />
//       </Head>

//       <Header />

//       <main>
//         {children}
//       </main>

//       <Footer />
//     </>
//   );
// }

// export default Layout;

import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Footer from "../../common/Footer";
import Header from "../header/Header";
import AdminLayout from "../admin/AdminLayout"; // AdminLayout import karein

function Layout({ children }) {
  const router = useRouter();

  const isPanelPage =
    router.pathname.startsWith("/admin-panel") ||
    router.pathname.startsWith("/attorney-panel") ||
    router.pathname.startsWith("/client-panel");

  // Sirf Admin Panel ke liye check
  const isAdminPanel = router.pathname.startsWith("/admin-panel");

  return (
    <>
      <Head>
        <title>Corelaw - Law firm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/images/icons/logo-icon.svg" />
      </Head>

      {!isPanelPage && <Header />}

      <main>
        {isAdminPanel ? (
          /* Automatic wrap all admin pages here */
          <AdminLayout>{children}</AdminLayout>
        ) : (
          children
        )}
      </main>

      {!isPanelPage && <Footer />}
    </>
  );
}

export default Layout;