import { useEffect, useState } from "react";
import Head from "next/head";

import Banner1 from "../components/banner/Banner1";


export default function Home() {
  

  return (
    <>
      
          <Head>
            <title>Lawfirm</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/images/icons/logo-icon.svg" />
          </Head>
          
          {/* <Header ... /> */}
          
          <Banner1 />
        
          {/* <Footer /> */}
        </>
      )}
  